### ISSUE TITLE
Setup GitHub Actions for CI on PR and Push Events

### ISSUE THREAD

**Issue by navin772** [LambdaTest/lambdatest-gradle-plugin#10]
There is no continuous integration (CI) setup for testing the code when a PR is opened or new code is pushed.

Setting up GitHub Actions for CI will help maintain code quality and catch issues early.

This is dependent on the Unit testing issue - #5, which can be utilized for testing in the CI.

**Comment by vihar-s1** [comment]
can I work on this issue for hacktoberfest ?

**Comment by navin772** [comment]
@vihar-s1 you can start you work on this but the CI needs to run the unit tests which will be added in #5

**Comment by vihar-s1** [comment]
ok @navin772
