### ISSUE TITLE
Setup Java Formatter Checks Using Checkstyle/Spotless in CI

### ISSUE THREAD

**Issue by navin772** [LambdaTest/lambdatest-gradle-plugin#11]
Adding Checkstyle/Spotless validations to the CI will ensure that all code follows the formatting rules before being merged.

Checkstyle GitHub Action on marketplace - [actions/checkstyle-for-java](https://github.com/marketplace/actions/checkstyle-for-java)

Update in the README file the steps to run the formatter locally before pushing the code.

**Comment by Taz03** [comment]
what do you think about [spotless](https://github.com/diffplug/spotless) it allows you to run spotlessApply and that'll fix all the styling issues automatically

**Comment by navin772** [comment]
@Taz03 thanks for the recommendation, we can go ahead with `spotless`!

Do you want to work on this issue?

**Comment by Taz03** [comment]
yea sure
