### ISSUE TITLE
Use Logging Framework (Log4j) for Better Logging

### ISSUE THREAD

**Issue by navin772** [LambdaTest/lambdatest-gradle-plugin#7]
The current implementation lacks a structured logging mechanism, making it difficult to trace and debug issues effectively.

Integrating a logging framework like `Log4j` will help improve observability.

Instead of `System.err.println()` we can use `Log4j` in java for logging.

**Comment by Taz03** [comment]
we want logging framework and comsumer right?

**Comment by subhramit** [comment]
> we want logging framework and consumer right?

Could you elaborate on "consumer"? I am interested in taking this.

**Comment by Taz03** [comment]
consumer is what actually prints the logs to the console, else it doesn't get printed unless the user setups a consumer

**Comment by subhramit** [comment]
> consumer is what actually prints the logs to the console, else it doesn't get printed unless the user setups a consumer

I have limited knowledge regarding this, but if I am not wrong -
1. Logging to "console" - Logger4j is sufficient for that.
2. Displaying the logs to the user via the frontend of the app - we will require a consumer (if I get you correctly)?

Do we just want 1 or both 1 and 2?

**Comment by Taz03** [comment]
only 1

**Comment by subhramit** [comment]
Cool, I'll take this.
