### ISSUE TITLE
Update and Test Dependencies

### ISSUE THREAD

**Issue by navin772** [LambdaTest/lambdatest-gradle-plugin#9]
The project dependencies might be outdated, which can cause security and compatibility issues.

Reviewing, updating and testing the new dependencies will keep the codebase secure and compatible.

**Comment by Delta456** [comment]
If you are updating the Java version as well then feel free to go with the inbuilt HTTP client.

**Comment by Taz03** [comment]
![image](https://github.com/user-attachments/assets/8ed1119f-7421-4853-9291-5024ef064b12)

we want stable version only right?

**Comment by Delta456** [comment]
Yes, we should go with the stable one.
